
(define (test-ref-gpu-array-copy rv src)
  (let* ((bv (gpu-array rv))
         (rows (gpu-rows rv)))
    (match (gpu-type rv)
     (0 ; vector
      (assert (= rows (array-length src)))
      (do ((i 0 (1+ i))) ((= i rows))
        (f32vector-set! bv i (array-ref src i))))
     (1
      (let ((cols (gpu-cols rv)))
        (assert (= (* cols rows)
                   (* (car (array-dimensions src)) (cadr (array-dimensions src)))))
        (do ((i 0 (1+ i))) ((= i rows))
        (do ((j 0 (1+ j))) ((= j cols))
          (array-set! bv (array-ref src i j) i j))))))))

(define-test (test-gpu-array-copy)
  (let ((test-array (lambda (arv brv)
                      (test-assert-arrays-equal (map (lambda (rv) (gpu-array rv))
                                                     (array->list arv))
                                                (map (lambda (rv) (gpu-array rv))
                                                     (array->list brv))
                                                0.004))))
    (loop-subtests (i)
      (let* ((rows (inexact->exact (truncate (+ 1 (* 64 (random-uniform))))))
             (cols (inexact->exact (truncate (+ 1 (* 64 (random-uniform))))))
             (rvs (gpu-make-vector rows))
             (rms (gpu-make-matrix rows cols))
             (rvd (gpu-make-vector rows))
             (rmd (gpu-make-matrix rows cols))
             (rvd2 (gpu-make-vector rows))
             (rmd2 (gpu-make-matrix rows cols)))
        (array-map! (gpu-array rvs) (lambda (x) (random-uniform)) (gpu-array rvs))
        (array-map! (gpu-array rms) (lambda (x) (random-uniform)) (gpu-array rms))
        (array-map! (gpu-array rvd) (lambda (x) (random-uniform)) (gpu-array rvd))
        (array-map! (gpu-array rmd) (lambda (x) (random-uniform)) (gpu-array rmd))
        (array-map! (gpu-array rvd2) (lambda (x) (random-uniform)) (gpu-array rvd2))
        (array-map! (gpu-array rmd2) (lambda (x) (random-uniform)) (gpu-array rmd2))
        (test-ref-gpu-array-copy rvd (gpu-array rvs))
        (test-ref-gpu-array-copy rmd (gpu-array rms))
        (gpu-array-copy rvd2 (gpu-array rvs))
        (gpu-array-copy rmd2 (gpu-array rms))
        (test-assert-arrays-equal (list (gpu-array rmd)) (list (gpu-array rmd2)) 0.001)
        (test-assert-arrays-equal (list (gpu-array rvd)) (list (gpu-array rvd2)) 0.001)))))

(define-test (test-gpu-sscal)
  (loop-subtests (i)
    (let* ((rows (inexact->exact (truncate (+ 1 (* 64 (random-uniform))))))
           (cols (inexact->exact (truncate (+ 1 (* 64 (random-uniform))))))
           (rvs (gpu-make-vector rows))
           (rms (gpu-make-matrix rows cols))
           (rvt (gpu-make-vector rows))
           (rmt (gpu-make-matrix rows cols)))
      ; setup reference and target array
      (array-map! (gpu-array rvs) (lambda (x) (random-uniform)) (gpu-array rvs))
      (array-map! (gpu-array rms) (lambda (x) (random-uniform)) (gpu-array rms))
      (array-map! (gpu-array rvt) (lambda (x) x) (gpu-array rvs))
      (array-map! (gpu-array rmt) (lambda (x) x) (gpu-array rms))
      ; do target sscal compute
      (gpu-dirty-set! rvt 1)
      (gpu-dirty-set! rmt 1)
      (gpu-sscal! 0.5 rvt)
      (gpu-sscal! 0.5 rmt)
      (gpu-refresh rvt)
      (gpu-refresh rmt)
      ; do reference compute
      (array-map! (gpu-array rvs) (lambda (x) (* 0.5 x)) (gpu-array rvs))
      (array-map! (gpu-array rms) (lambda (x) (* 0.5 x)) (gpu-array rms))
      (test-assert-arrays-equal (list (gpu-array rvs)) (list (gpu-array rvt)) 0.0001)
      (test-assert-arrays-equal (list (gpu-array rms)) (list (gpu-array rmt)) 0.0001))))
